# vscode 安装 rest client插件 
@url=http://127.0.0.1:7001/
###
GET {{url}}
###
POST {{url}}login
Content-Type: application/json

{
    "name": "liho",
    "password": "123456",
    "type": 1
}


# ###
# GET {{url}}
# ###
# # GET http://localhost:3000/about
# GET {{url}}about
# ###
# POST {{url}}products
# Content-Type: application/json

# {
#     "title": "产品4"
# }
# ###
# PUT {{url}}products/id
# Content-Type: application/json

# {
#     "title": "产品44"
# }
# ###
# DELETE {{url}}products/id
# ###
# POST {{url}}
# Content-Type: application/json

# {
#     "id": "1",
#     "test": " POST请求"
# }
